SOURCES_DIRECTORY = sources
BINARIES_DIRECTORY = binaries
COMPILER = g++
COMPILER_OPTIONS = -std=c++11 -Oz -Wall -Wextra -Werror

all: ${BINARIES_DIRECTORY}/reveal

clean:
	rm -rf ${BINARIES_DIRECTORY}

${BINARIES_DIRECTORY}/%: ${SOURCES_DIRECTORY}/%.cpp
	mkdir -p ${BINARIES_DIRECTORY}
	${COMPILER} ${COMPILER_OPTIONS} -o ${@} ${<}
