SOURCES_DIRECTORY  = sources
BINARIES_DIRECTORY = binaries
COMPILER           = cc
COMPILER_OPTIONS   = -Oz -Wall

all: ${BINARIES_DIRECTORY}/reveal

${BINARIES_DIRECTORY}/%: ${SOURCES_DIRECTORY}/%.c
	mkdir -p ${BINARIES_DIRECTORY}
	${COMPILER} ${COMPILER_OPTIONS} ${<} -o ${@}

clean:
	rm -rf ${BINARIES_DIRECTORY}

