.TH revelio 1 MANDATE
.SH NAME
.PP
revelio - it reveals info about file system entries.

.SH SYNOPSIS
.PP
revelio [\fIOPTION\fP | \fIPATH\fP]...

.SH DESCRIPTION
.PP
It reveals one or multiple info types about the entry \fIPATH\fP(s) given as
arguments based on the \fIOPTION\fP(s) placed before each of them.

.SH INFO TYPE OPTIONS
.PP
Use these options before entry paths to set the info type to be retrieved. If
none is used, the one marked as default is considered.

.TP
.B \-c
(default) reveal its contents. For files, it will be their contents; For
directories, their entries; and for unfollowed symlinks, what they point to.
.TP
.B \-t
reveals its type: regular (r), directory (d), symlink (l), character (c),
block (b), socket (s) or fifo (f).
.TP
.B \-s
reveals its byte size.
.TP
.B \-hs
reveals its size using the most convenient unit for a human read.
.TP
.B \-p
reveals its read (r), write (w), execution (x) and lack (-)  permissions for
user, group and others.
.TP
.B \-op
reveals its permissions in octal base.
.TP
.B \-u
reveals the user that owns it.
.TP
.B \-ui
reveals the UID of the user that owns it.
.TP
.B \-g
reveals the group that owns it.
.TP
.B \-gi
reveals the GID of the group that owns it.
.TP
.B \-md
reveals its last modified date.

.SH SYMLINK OPTIONS
.PP
Use these options before entry paths to set how symlinks are handled. If
none is used, the one marked as default is considered.

.TP
.B \-ul
(default) unfollows symlinks.
.TP
.B \-fl
follows symlinks.

.SH EXAMPLES
.PP
# reveals the entries in the current directory.
.br
revelio .

.PP
# reveals the type of some unknown entries.
.br
revelio -t ../entry{1,2}

.PP
# reveals the permissions of a file and current directory.
.br
revelio -p file.txt -op .

.PP
# combine it with wildcards and utilities.
.br
revelio -t ~/.*
.br
revelio /usr/bin | fmt
.br
date --date="$(revelio -md file.conf)" +"%H:%M"

.SH EXIT STATUS
.PP
It returns 0 on success, and 1 otherwise.

.SH SOURCE CODE
.PP
Its source code is available at <https://github.com/skippyr/revelio>.

.SH BUGS
.PP
Report bugs at <https://github.com/skippyr/revelio/issues>.

.SH COPYRIGHT
.PP
See LICENSE for copyright and license details.
